AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notifica-zap-service

Globals:
  Function:
    Timeout: 3

Resources:
  NotificaZapService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: notifica_zap_service/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole  # Permissões básicas para logs
        - AWSLambda_FullAccess         # Permissão para invocar outras funções Lambda
      Events:
        NotificaZapApi:
          Type: Api
          Properties:
            Path: /zap
            Method: post  # Alterado para POST, considerando a funcionalidade de envio

Outputs:
  NotificaZapApi:
    Description: "API Gateway endpoint URL for Prod stage for Notifica Zap Service"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/notify/"
  NotificaZapFunction:
    Description: "Notifica Zap Lambda Function ARN"
    Value: !GetAtt NotificaZapService.Arn
  NotificaZapFunctionIamRole:
    Description: "Implicit IAM Role created for Notifica Zap function"
    Value: !GetAtt NotificaZapServiceRole.Arn
