#!/bin/bash


PAGES_DIR="./src/app"

DYNAMIC_LINE="export const dynamic = 'force-static';"

# Percorre todos os arquivos .tsx dentro de /app
find "$PAGES_DIR" -type f -name "*.tsx" | while read FILE
do
  sed -i.bak "/^$DYNAMIC_LINE$/d" "$FILE" && rm "${FILE}.bak"
  echo "❌ Removido de: $FILE"
done
