# Generated by Django 5.1.6 on 2025-03-23 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('telefone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
                ('qtd_imoveis', models.IntegerField(default=0, verbose_name='Quantidade de Imóveis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Administradora',
                'verbose_name_plural': 'Administradoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('cep', models.CharField(max_length=20, verbose_name='CEP')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('administradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominios', to='imoveis.administradora', verbose_name='Administradora')),
            ],
            options={
                'verbose_name': 'Condomínio',
                'verbose_name_plural': 'Condomínios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bloco')),
                ('numero_unidade', models.CharField(max_length=50, verbose_name='Número da Unidade')),
                ('cep', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP')),
                ('numero_pasta', models.CharField(max_length=25, unique=True, verbose_name='Número da Pasta')),
                ('cpf_proprietario', models.CharField(max_length=25, unique=True, verbose_name='CPF do Proprietário')),
                ('nome_proprietario', models.CharField(max_length=150, verbose_name='Nome do Proprietário')),
                ('login', models.CharField(blank=True, max_length=100, null=True, verbose_name='Login')),
                ('senha', models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='imoveis.condominio', verbose_name='Condomínio')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['condominio', 'numero_unidade'],
            },
        ),
    ]
