# Generated by Django 5.1.6 on 2025-04-02 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_remove_unidade_proprietario_alter_unidade_condominio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='condominio',
            field=models.ForeignKey(help_text='Refere-se à unidade responsável por esse condomínio.', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='imoveis.condominio', verbose_name='Condomínio da qual a unidade faz parte'),
        ),
    ]
