# Generated by Django 5.1.6 on 2025-03-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0002_alter_cliente_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
