# Generated by Django 5.1.6 on 2025-03-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0004_alter_usuario_options_alter_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='E-mail'),
        ),
    ]
