# Generated by Django 5.1.6 on 2025-03-24 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0005_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='operacional.cliente', verbose_name='Cliente'),
        ),
    ]
