# Generated by Django 5.1.6 on 2025-03-24 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0007_perfil_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
    ]
