# Generated by Django 5.1.6 on 2025-03-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0008_remove_usuario_first_name_remove_usuario_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(default=0, max_length=200, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
    ]
