# Generated by Django 5.1.6 on 2025-03-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0009_usuario_sobrenome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='usuario',
            name='entrada_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Entrada em'),
        ),
    ]
