# Generated by Django 5.1.6 on 2025-03-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0011_remove_usuario_password_usuario_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=0, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
