# Generated by Django 5.1.6 on 2025-03-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0012_remove_usuario_senha_usuario_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
