name: Propius Backend Deploy

# O GitHub Actions acessa o servidor via SSH (usando sua chave privada salva nos secrets).
# O servidor precisa acessar o GitHub para clonar o repositório.
# Para isso, o servidor precisa de uma chave SSH válida autorizada no repositório (deploy key).

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

# ssh -i ~/.ssh/propius_deploy_key root@212.56.42.99

jobs:
  propius-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PROPIUS_SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 212.56.42.99 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy Backend to CONTABO SERVER
        run: |
          echo "Deploying backend to CONTABO SERVER"
          ssh -o StrictHostKeyChecking=no root@212.56.42.99 << 'EOF'
            set -e

            echo "[STEP 1] Criando/entrando no diretório do projeto"
            PROJECT_DIR="/root"

            if [ ! -d "$PROJECT_DIR" ]; then
              echo "  > Diretório não existe, criando e clonando o repo"
              mkdir -p "$PROJECT_DIR"
              cd "$PROJECT_DIR"
            else
              echo "  > Diretório já existe"
              cd "$PROJECT_DIR"
            fi
            echo "[✓] Diretório pronto"

            echo "Listing files in current directory:"
            ls -la

            echo "[STEP 2] Atualizando código"

            echo "  > Limpando diretório do projeto para garantir clone limpo"
            rm -rf "${PROJECT_DIR:?}"/* "${PROJECT_DIR:?}"/.??* || true

            echo "  > Clonando repositório"
            if [ -d ".git" ]; then
                echo "  > Repositório já clonado, atualizando"
                git reset --hard
                git clean -fd
                git fetch origin production
                git checkout production
                git pull origin production
            else
                echo "  > Clonando repositório pela primeira vez"
                git clone --branch production git@github.com:davifati/administramosImoveis.git  || exit 1
            fi
                
            echo "[✓] Código atualizado"

            echo "Listing files in current directory:"
            ls -la

            echo "[STEP 3] Entrando no diretório do projeto - propius/backend"
            cd administramosImoveis/propius/backend || exit 1

            echo "Listing files in current directory:"
            ls -la

            echo "[STEP 4] Instalando e configurando Pyenv"
            echo "  > Instalando dependências necessárias"
            sudo apt update
            sudo apt install -y make build-essential libssl-dev zlib1g-dev \
            libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
            libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev || exit 1
            
            echo "  > Removendo instalação anterior do Pyenv"
            rm -rf /root/.pyenv || exit 1
            
            echo "  > Instalando Pyenv"
            curl https://pyenv.run | bash || exit 1

            echo "  > Configurando Pyenv"
            echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
            echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
            echo 'eval "$(pyenv init - bash)"' >> ~/.bashrc
            echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
            
            # Ensure pyenv is available in current session
            export PYENV_ROOT="$HOME/.pyenv"
            [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init - bash)"
            eval "$(pyenv virtualenv-init -)"

            echo "  > Instalando Python 3.10 com Pyenv"
            $PYENV_ROOT/bin/pyenv install 3.10.0 || exit 1
            $PYENV_ROOT/bin/pyenv global 3.10.0 || exit 1

            echo "[STEP 5] Ativando/criando ambiente virtual"
            echo ""
            if [ ! -d "venv" ]; then
              echo "  > venv não encontrado, criando"
              python -m venv venv || exit 1
            fi
            source venv/bin/activate || exit 1
            echo "[✓] Ambiente virtual pronto com Python 3.10"

            echo "[STEP 6] Instalando dependências"
            echo ""
            pip install -r requirements.txt || exit 1
            echo "[✓] Dependências instaladas"

            echo "[STEP 7] Rodando migrações"
            echo ""
            python manage.py migrate || exit 1
            echo "[✓] Migrações aplicadas"

            # echo "[STEP 7] Coletando arquivos estáticos"
            # python manage.py collectstatic --noinput || exit 1
            # echo "[✓] Arquivos estáticos coletados"

            echo "[STEP 8] Reiniciando serviços (comentado por enquanto)"
            # sudo systemctl restart gunicorn || sudo supervisorctl restart myapp || exit 1
            # sudo systemctl restart nginx || exit 1
            # echo "[✓] Serviços reiniciados"

            echo "[✓] Deploy finalizado com sucesso"
            exit 0
          EOF

      - name: Deploy Backend to CONTABO SERVER
        run: |
          echo "Deploying Frontend to CONTABO SERVER"
